baseURL: https://amitjavilaventura.github.io/
publishDir: docs
languageCode: en-us
title: Adrià Mitjavila Ventura
theme: minimal
disqusShortname: amitjavila
googleAnalytics: ''
pluralizelisttitles: no
content: yes
params:
  homeIcons: yes
  backgroundPic: "/images/portada.png" ## background pic of the first pages
  favicon: "/images/dna_numeros2.png"  ## favicon in the browser tab
  profilePic: "/images/fotojo.png" ## logo in the first page
  accent: darkred
  author: "Adrià Mitjavila Ventura"
  titleFont: papyrus
  backgroundColor: white
  description: Biotechnologist around computers
  font: Raleway
  githubUsername: 'amitjavilaventura'
  highlight: yes
  highlightLanguages:
    - r
    - python
    - bash
  highlightStyle: default
  showBorder: yes
  permalink: posts
  #css: "css/custom.css"
menu:
  icon:
    - name: fas fa-at
      url: mailto:adria.mitjavila94@gmail.com
      weight: 1
    - name: fab fa-github
      url: https://github.com/amitjavilaventura/
      weight: 2
    - name: fab fa-gitlab
      url: https://gitlab.com/amitjavilaventura/
      weight: 3
    - name: fab fa-bitbucket
      url: https://bitbucket.org/amitjavilaventura/
      weight: 4
    - name: fab fa-orcid
      url: https://orcid.org/0000-0002-0337-1929
      weight: 5
    - name: fab fa-stack-overflow
      url: https://stackoverflow.com/users/14525301/adri%c3%a0-mitjavila-ventura
      weight: 6
    - name: fab fa-linkedin
      url: https://www.linkedin.com/in/adria-mitjavila-ventura/
      weight: 7
    - name: fab fa-twitter
      url: https://twitter.com/adriamitjavila/
      weight: 9

  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Posts
      url: /posts/
      weight: 3
    - name: Research
      url: /research/
      weight: 4
    - name: Publications
      url: /publications/
      weight: 5
    - name: Code
      url: /code/
      weight: 6
    - name: Curriculum
      url: /cv/  ##https://amitjavilaventura.github.io/CVs/
      weight: 7

markup:
  goldmark:
    renderer:
      unsafe: true
