---
title: "Download my CV"
description: |
  Short and long PDF versions of my CV/resume
output:
  distill::distill_article:
    toc: false
    toc_float: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      error = FALSE,
                      warning = FALSE, 
                      fig.align = "center")
```

```{r image_me, eval = F}
htmltools::img(src = "assets/foto_jo.jpg", 
               alt = 'foto_carnet', 
               style = 'float; position:absolute; top:1; right:0; padding-top:10px; padding-bottom:35px; padding-right:200px; height:200px')
```


<p align='justify'>Here I have two versions of my CV that can be downloaded in PDF format:</p>

* <p align='justify'>A short version of my CV / resume.</p>
* <p align='justify'>A longer CV version.</p>

```{r fig.cap="Adrià Mitjavila Ventura | Resume", layout="l-site"}
knitr::include_url("assets/amitjavila_cv_short.pdf")
```

<br>

```{r fig.cap="Adrià Mitjavila Ventura | CV", fig.layout="l-site"}
knitr::include_url("assets/mitjavila_adria_cv.pdf")
```

<br>

***

<p align='justify'> Please, have in mind that these documents might not be fully updated, so if you need more information, do not hesitate to contact me.</p>
