---
title: "Publications"
description: |
  Journal articles, posters...
output:
  distill::distill_article:
    toc: yes
    toc_float: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      error = FALSE,
                      warning = FALSE, 
                      fig.align = "center")
```

# Journal articles

* <p align='justify'> Begley V, Jordán-Pla A, Peñate X, Godino-Garrido A, Challal D, Cuevas-Bermúdez A, <ins style="color:Tomato;">Mitjavila A</ins>, Barucco Mara, Gutiérrez G, Singh A, Alepuz P, Navarro F, Libri D, Pérez-Ortín JE, Chávez S (2020). **Xrn1 influence on gene transcription results from the combination of general effects on elongating RNA pol II and gene-specific chromatin configuration**. *RNA Biology*. [doi: 10.1080/15476286.2020.1845504](https://doi.org/10.1080/15476286.2020.1845504).</p>

```{r eval=FALSE, echo=FALSE}
# Posters

<p align='justify'> At the moment, I do not have any presented posters.</p>
```