---
pagetitle: "Adrià Mitjavila Ventura"
title: "<b style='color:black;'>Research experience</b>"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      error = FALSE,
                      warning = FALSE, 
                      fig.align = "center")
```

***

<p style='font-size:20px; color:black;'> <b>Pasini's lab, <i>Istituto Europeo di Oncologia</i></b>
<br> <i style='font-size:15px;'> July 2019 - Present </i></p>

<p style='font-size:15px;'>Insert research here</p>

***

<p style='font-size:20px; color:black;'> <b>Gene expression lab, <i>Instituto de Biomedicina de Sevilla</i></b><br>
<i style='font-size:15px;'> September 2017 - October 2018 </i></p>

<p style='font-size:15px;'>In the context of the master's thesis (<i>Universidad de Sevilla</i>), under the supervision of Dr. Sebastián Chávez de Diego and Dr. Gabriel Gutierrez Pozo and within Dr. Victoria Begley's PhD project, I started studying Xrn1, a protein involved in the degradation of mRNA, and it's role in the nucleosome localization and transcription in <i>Saccharomyces cerevisiae</i>. Using MNase-seq and following a DANPOS-based analysis, we found that the Xrn1 knockout mutant strains had higher nucleosome occupancy around TSS, which we related with a lower transcription initiation compared to WT strains, whereas in the gene body, the nucleosome occupancy was diminished as a consequence of RNA pol II backtracking. Results were validated using MNase-qPCR of two selected genes in Xrn1 conditional mutants. </p> 

<p style='font-size:15px;color:black;'>My contribution to this research was: </p>

* <p style='font-size:15px;'>Performing the bioinformatic analysis of the MNase-seq data.</p>
* <p style='font-size:15px;'>Performing the MNase-qPCR validation, including the yeast culture, the MNase-driven DNA digestion, the design of the primers and the following qPCRs.</p>

<p style='font-size:15px;color:black;'> Master's thesis: <em style='font-size:15px;color:gray;'> Influence of Xrn1 in nucleosome positioning across <ins>Saccharomyces cerevisiae</ins> genome and its effects in transcription</em>.</p>

<p style='font-size:15px;color:black;'> Related publications: </p>


***

<p style='font-size:20px; color:black;'> <b>Intestinal microbial ecology, <i>Microbial, S.L.</i></b>
<br> <i style='font-size:15px;'> September 2016 - June 2017 </i></p>

<p style='font-size:15px;'> In the context of the bachelor's thesis (<i>Universitat de Girona</i>) and under the supervision of Prof. Jesús García-Gil, I studied the diversity of the ileal mucosa-related microbiota of colorectal cancer patients submitted to an ileostomy and its changes after a butyrate treatment. Using DNA extracted from human biopsies of ileal mucosa, we performed qPCR and high-throughput sequencing followed by a SPSS-based statistical analysis of to test the differences between the butyrate-treated, placebo-treated and untreated groups, and we found that some healthy-related butyrate-producing bacteria increased in proportion after the butyrate-treated, but not in the other groups. At the same time, different disease-related bacteria were found to decrease in the butyrate group after the treatment compared to the other groups. Although the changes weren't higly robust in terms of significancy, the short-period of the treatment (4 weeks) and its conditions (ileostomy allows oxigen to enter the ileum, which is supposed to be an anoxic environment) made us think that a long-term butyrate treatment could improve microbiological conditions in the studied patients.</p>

<p style='font-size:15px;color:black;'> My contribution to this research was:</p>

* <p style='font-size:15px;'>Performing the DNA extractions of the intestinal biopsies.</p>
* <p style='font-size:15px;'>Performing qPCR analyses to detect and quantify some of the crucial bacterial families and genders.</p>
* <p style='font-size:15px;'>Performing the SPSS-based statistical analysis for the high-throughput sequencing-derived data.</p>
* <p style='font-size:15px;'>Performing qPCR analyses to detect and quantify some of the species found to be increased in the sequencing data.</p>

<p style='font-size:15px;color:black;'> Bachelor's thesis title: <em style='font-size:15px;color:gray;'> Butyrate-induced changes in the diversity of intestinal mucosa-associated microbiota in colorectal cancer patients submitted to a lateral ileostomy </em>.</p>





<br><br><br><br>
<br><br><br><br>
<br><br><br><br>