---
title: "About me"
description: "Some details about my life"
---

---

<style>
    p {text-align: justify;}
</style>

### Interests

My interests are mainly focused in the analysis of transcriptomics and epigenomics data, as well as in software and pipeline development. Currently, I am interested in small RNAs, more specifically piRNAs.

On the other hand, I declare myself as an R and R Markdown lover, but I am in an open relationship with them, so I am eager to learn and use other languages such as Bash and Python.

***

### Academic career

I began my journey in science with a BSc in Biotechnology, during which I did a professional internship in a company dedicated to molecular and microbial analyses of food and water for pathogen detection and food forensics. I carried the bachelor's thesis in the same company by analyzing the microbial composition of the illeal mucosa of colorectal cancer patients submitted to a colectomy and ileostomy in response to a butyrate treatment. 

After graduating, I studied a MSc in Molecular Genetics, where I initiated to bioinformatics. During the thesis, I spent the whole year studying the role of the protein Xrn1 in nucleosome architecture and gene transcription in budding yeast. 

Then, I enrolled on a MSc in Bioinformatics in which I am learning the basic tools and statistical knowledge behind the analyses of large amounts of biological data. 

In 2019, until 2021, I moved to Milan where I worked as a bioinformatician and collaborated in several projects studying epigenetic mechanisms and signaling pathways -mainly Wnt/$\beta$catenin- underlying cell differentiation and oncogenesis.

Recently, I returned home to continue my career in bioinformatics in the [Regulatory Genomics group](https://www.carrerasresearch.org/en/regulatory-genomics) of the [Josep Carreras Leukaemia Research Institute](https://www.carrerasresearch.org/en).

***

### Outside of academia

As a plus, I have been an active member from the [*Associació de Biotecnòlegs de Catalunya (ASBTEC)*](https://asbtec.cat) -an association dedicated to promotion of the biotechnologists to Catalan society- since 2018 and board member since 2019, collaborating in the organization of diverse Biotechnology-related events (e.g. job search, entrepreneurship, divulgation, different research topics...) and leading the team in charge of communication and divulgation through social networks, our webpage and other activities.

<br>

Furthermore, one of my hobbies is communicating science and for this reason I have recently started [BioBit](https://biobit.netlify.app), a blog dedicated to spread Bioinformatics, although its main goal is to study about what I write. Also I started [Perill Biologic](https://perillbiologic.netlify.app), another blog to communicate Biology in Catalan. 

<br>

***

### In sport

On the other hand, during most of my academic career, I have combined the science studies with high-level training and competition in rowing, achieving excellent results in both, national and international competitions.

I started rowing in 2007 and my first international competition was *La Coupe de la Jeunesse* in 2011. In 2016, together with my double mate, I missed the Olympic qualification for only one place and, after that, we became World Rowing Under-23 Champions in the lightweight men's double scull (BLM2x).

<br>

After many years training at my highest level, I left elite rowing in 2019, after being 7^th^ in the European Rowing Championship, just before moving to Milan to work as a bioinformatician. I haven't competed since then, but one cannot leave rowing that easily and I pretend to compete again at a more local level.
