---
title: "Microbial. Sistemes i aplicacions analítiques, S.L."
description: "Molecular Microbiology"
weight: 10
---

<style>
    p {text-align: justify;}
</style>

## Molecular Microbiology, <a href="https://www.microbial-systems.com/"  target="_blank"><em>Microbial, S.L.</em></a>

<p style='font-size:15xpx;color:gray'><em style='color:black;'>September 2016 - June 2017</em><br>
Internship and Bachelor's thesis student</p>

In the context of my bachelor's thesis (*BSc in Biotechnology*) and under the supervision of Prof. Jesús García-Gil, I studied the diversity of the ileal mucosa-related microbiota of colorectal cancer patients submitted to an ileostomy and its changes after a butyrate treatment. Using DNA extracted from human biopsies of ileal mucosa, we performed qPCR and high-throughput sequencing followed by a SPSS-based statistical analysis to search for the differences between the butyrate-treated, placebo-treated and untreated groups, and we found that some healthy-related butyrate-producing bacteria increased in proportion after the butyrate-treated, but not in the other groups. At the same time, different disease-related bacteria were found to decrease in the butyrate group after the treatment compared to the other groups. Although the changes weren't higly robust in terms of significancy, the short-period of the treatment (4 weeks) and its conditions (ileostomy allows oxigen to enter the ileum, which is supposed to be an anoxic environment) made us think that a long-term butyrate treatment could improve microbiological conditions in the studied patients.

---

<ins>My contributions to this research were:</ins>


* Performing the DNA extractions of the intestinal biopsies. <br>
* Performing qPCR analyses to detect and quantify some of the crucial bacterial families and genera. <br>
* Performing the SPSS-based statistical analysis for the high-throughput sequencing-derived data. <br>
* Performing qPCR analyses to detect and quantify some of the species found to be increased in the sequencing data. <br>


---

<ins>Bachelor's thesis:</ins>

* <em> Butyrate-induced changes in the diversity of intestinal mucosa-associated microbiota in colorectal cancer patients submitted to a lateral ileostomy. </em>