---
title: "Instituto de Biomedicina de Sevilla"
description: "Gene Expression & Bioinformatics"
weight: 9
---

<style>
    p {text-align: justify;}
</style>

## <a href="https://www.ibis-sevilla.es/investigacion/oncohematologia-y-genetica/expresion-genica/chavez-de-diego-sebastian.aspx" target="_blank">Gene expression lab</a>, <a href="https://www.ibis-sevilla.es/"  target="_blank"><i>Instituto de Biomedicina de Sevilla</i></a>

<p style='font-size:15px;color:gray'><em style='color:black;'>*September 2017 - October 2018*</em><br>
Master's thesis student and research assistant</p>

---

In the context of the master's thesis (*MSc in Molecular Genetics & Biotechnology*), under the supervision of Dr. Sebastián Chávez de Diego and Dr. Gabriel Gutierrez Pozo and within Dr. Victoria Begley's PhD project, I started studying Xrn1, a protein involved in the degradation of mRNA, and it's role in the nucleosome localization and transcription in *Saccharomyces cerevisiae*. Using MNase-seq and following a DANPOS-based analysis, we found that the Xrn1 knockout mutant strains had higher nucleosome occupancy around TSS, which we related with a lower transcription initiation compared to WT strains, whereas in the gene body, the nucleosome occupancy was diminished as a consequence of RNA pol II backtracking. Results were validated using MNase-qPCR of two selected genes in Xrn1 conditional mutants.

---

<ins>My contributions to this research were:</ins>

* Bioinformatic analysis of the MNase-seq data. <br>
* MNase-qPCR validation, including the yeast culture, the MNase-driven DNA digestion, the design of the primers and the following qPCRs.


---

<ins>Related publications:</ins>

* Begley *et al* (2020). **Xrn1 influence on gene transcription results from the combination of general effects on elongating RNA pol II and gene-specific chromatin configuration**. *RNA Biology*. [doi: 10.1080/15476286.2020.1845504](https://doi.org/10.1080/15476286.2020.1845504){target="_blank"}.


---

<ins>Master's thesis:</ins>

* *Influence of Xrn1 in nucleosome positioning across </em>Saccharomyces cerevisiae<em> genome and its effects in transcription.*
