---
title: "Istituto Europeo di Oncologia"
description: "Epigenetics & Bioinformatics"
weight: 7
---

<style> 
  p { text-align: justify; }
</style>

## Pasini's lab, <a href="https://www.research.ieo.it/" target="_blank"><i>Istituto Europeo di Oncologia</i></a>

<p style='font-size:15px;color:gray'><em style='color:black;'>*July 2019 - Present*</em><br>
Bioinformatician and PhD candidate</p>

---

In the context of my PhD, under the direct supervision of Dr. Diego Pasini and together with Dr. Daria Manganaro, I started my project with the aim of dissecting the role of the Wnt/&beta;catenin pathway in colorectal cancer initiation and progression.

---

<span style="text-decoration:underline">My contribution to this research was:</span>

<p align='justify'>
* Comparison of different ATACseq peak callers. <br>
* Comparison of different sequencing depths in RNAseq. <br>
* Development of an ATACseq pipeline to run using Snakemake. The code can be visualized [here](https://github.com/amitjavilaventura/ATACseq-snakemake) (still ongoing). <br>
* Development of a ShinyApp to allow wetlab members to visualize the omics produced in the lab in an easy way. The code can be visualized [here](https://github.com/amitjavilaventura/DPomics). <br>
* Analysis of transcriptomics (RNAseq), cistromics (ChIPseq) and DNA accessibility data (ATACseq). <br>
</p>


<!--
* Analysis of the CRC-related ignorome.
-->

<!--
---
<span style="text-decoration:underline">Related publications:</span>
-->

<!--
---
<span style="text-decoration:underline">Collaborations:</span>
-->


