---
title: "Institut Josep Carreras"
description: "Regulatory Genomics & Bioinformatics"
weight: 7
draft: false
---

<style>
    p {text-align: justify;}
</style>

## <a href="https://www.carrerasresearch.org/en/regulatory-genomics" target="_blank">Vavouri's lab</a>, <a href="https://www.carrerasresearch.org/en" target="_blank"><i>Institut Josep Carreras</i></a>

<p style='font-size:15px;color:gray'><em style='color:black;'>*August 2021 - Present*</em><br>
Bioinformatician & master's thesis student</p>

---

Under the supervision of Dr. Tanya Vavouri, I am studying the PIWI-interacting RNAs (piRNAs) and their biogenesis. In January of 2022, I completed my master's thesis (MSc in Bioinformatics and Biostatistics, UOC) with honors, where I analyzed the piRNA variation across closely related species and the factors influencing this variation.

---

<ins>My contributions to this research have been:</ins>

* Development of a pipeline to pre-process small RNA-seq data with focus to the analysis of piRNAs.
* Retrieve and analyze multiple-sequence alignments using [ENSEMBL Compara Perl API](https://www.ensembl.org/info/docs/api/compara/index.html).
* Development of an approach for differential expression analysis without gene length differences when comparing multiple species. 
* Mentoring bachelor's and master's thesis students.

<!--
---

<ins>Related publications:</ins>

-->

---

<ins>Master's thesis:</ins>

* *Analysis of the variation in piRNA expression across three </em>Mus<em> species.*

