---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: templates/custom.tex
geometry: margin=1in

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 9pt
linkcolor: blue
urlcolor: blue

title: "CV"
author: Adrià Mitjavila Ventura

jobtitle: "Bioinformatician"
address: "Girona (Spain) - Milan (Italy)"
fontawesome: yes
email: adria.mitjavila94@gmail.com
github: amitjavilaventura
gitlab: amitjavilaventura
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
web: "amitjavilaventura.github.io"

keywords: R Markdown, academic CV, template

updated: yes
---

\vspace{3mm}

\small 
\emph{Biotechnologist living around computers, pursuing a PhD in Computational Biology and interested in data analysis to support experimental research as well as in pure computational experiments and in software/pipeline development.}

\normalsize


# Education \hrulefill

*Scuola Europea di Medicina Molecolare*, PhD. Computational Biology \hfill {\small\emph{2019 - Present}}

*Universitat Oberta de Catalunya*, MSc. Bioinformatics and Biostatistics \hfill {\small\emph{2018 - Present}}

*Universidad de Sevilla*, MSc. Molecular Genetics and Biotechnology \hfill {\small\emph{2017 - 2018}}

*Universitat de Girona*, BSC. Biotechnology \hfill {\small\emph{2012 - 2017}}


# Employment \hrulefill

*Istituto Europeo di Oncologia*  \hfill {\small\textbf{Milan (Italy)}}

* \footnotesize PhD Candidate in Computational Biology \hfill \emph{10/2019 - Present}

* \footnotesize Bioinformatician \hfill \emph{07/2019 - 10/2019}

```{r eval=FALSE, echo=FALSE}
*Universitat Oberta de Catalunya*  \hfill {\small\textbf{Online}}

* \footnotesize Master's thesis student \hfill \emph{10/2020 - Present}
```

*Instituto de Biomedicina de Sevilla* \hfill {\small\textbf{Seville (Spain)}}

* \footnotesize Research assistant \hfill \emph{07/2018 - 10/2018}

* \footnotesize Master's thesis student \hfill \emph{09/2017 - 07/2018}

*Institut d'Investigació Biomèdica de Girona* \hfill {\small\textbf{Girona (Spain)}}

* \footnotesize Research internship student \hfill \emph{07/2017 - 09/2017}

*Microbial. Sistemes i aplicacions analítiques, S.L.* \hfill {\small\textbf{Girona (Spain)}}

* \footnotesize Bachelor's thesis student \hfill \emph{01/2017 - 06/2017}

* \footnotesize Internship student \hfill \emph{09/2016 - 06/2017}


# Publications \hrulefill

## Journal Articles

\footnotesize Begley *et al*. 2020 **Xrn1 influence on gene transcription results from the combination of general effects on elongating RNA pol II and gene-specific chromatin configuration**. *RNA Biology*. DOI: [10.1080/15476286.2020.1845504](https://doi.org/10.1080/15476286.2020.1845504).


# References \hrulefill

\footnotesize Available upon request.